"""
reporting/report.py
-------------------
HackerOne / Bugcrowd report generator.
"""

from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional

from core.logger import get_logger, banner, info, ok, warn
from core.utils import ensure_dir, safe_filename
from core.database import get_db
from reporting.cvss_calculator import cvss_for
from reporting.poc_generator import poc_for_finding

log = get_logger("report")


H1_TEMPLATE = """# {title}

**Severity:** {severity} (CVSS {score})
**Vector:** `{vector}`
**Target:** {host}
**Vulnerability Type:** {vuln_type}

## Summary

{summary}

## Steps To Reproduce

{steps}

## Impact

{impact}

## Remediation

{remediation}

---

*Report generated by Dream Framework on {ts}*
"""


def _default_steps(url, param, payload):
    lines = ["1. Navigate to: " + url]
    if param and payload:
        lines.append("2. Inject payload into parameter: " + param)
        lines.append("3. Payload: " + payload)
    lines.append("4. Observe the response confirming the vulnerability.")
    return "\n".join(lines)


def _default_impact(vuln_type):
    v = vuln_type.lower()
    if "sql" in v:
        return "An attacker can read or modify database contents."
    if "xss" in v:
        return "Session hijacking, credential theft, or arbitrary actions."
    if "ssrf" in v:
        return "Internal network access, cloud metadata theft."
    if "idor" in v:
        return "Unauthorized access to other users' data."
    if "takeover" in v:
        return "Attacker can host arbitrary content on subdomain."
    if "jwt" in v:
        return "Authentication bypass / privilege escalation."
    if "redirect" in v:
        return "Phishing / token leakage."
    if "xxe" in v:
        return "File disclosure, SSRF, or DoS."
    if "ssti" in v:
        return "Remote code execution in template engine."
    return "Security impact varies - review evidence."


def _default_remediation(vuln_type):
    v = vuln_type.lower()
    if "sql" in v:
        return "Use parameterized queries / prepared statements."
    if "xss" in v:
        return "Context-aware output encoding and CSP."
    if "ssrf" in v:
        return "Whitelist destinations; block link-local addresses."
    if "idor" in v:
        return "Enforce authorization on every object access."
    if "takeover" in v:
        return "Remove dangling DNS records; reclaim resources."
    if "jwt" in v:
        return "Use strong secrets; reject none alg; validate kid."
    if "redirect" in v:
        return "Whitelist redirect targets."
    if "xxe" in v:
        return "Disable external entity processing."
    if "ssti" in v:
        return "Never render user input as templates."
    return "Apply defense-in-depth and follow OWASP guidelines."


def build_report_md(finding, domain):
    vuln_type = finding.get("vuln_type", "unknown")
    cvss = cvss_for(vuln_type)
    url = finding.get("url", "")
    param = finding.get("param", "")
    payload = finding.get("payload", "")

    from urllib.parse import urlparse
    host = urlparse(url).netloc if url else domain

    title = vuln_type.replace("_", " ").title() + " in " + host
    summary = "A " + vuln_type + " vulnerability was detected at " + url + "."
    steps = _default_steps(url, param, payload)
    impact = _default_impact(vuln_type)
    remediation = _default_remediation(vuln_type)

    return H1_TEMPLATE.format(
        title=title,
        severity=cvss["severity"],
        score=cvss["score"],
        vector=cvss["vector"],
        host=host,
        vuln_type=vuln_type,
        summary=summary,
        steps=steps,
        impact=impact,
        remediation=remediation,
        ts=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )


def generate_reports(domain, scan_id=None, output_root="results",
                     only_severity=None, use_ai=False):
    banner("REPORTS: " + domain)

    out_dir = Path(output_root) / domain / "reports"
    ensure_dir(out_dir)

    db = get_db()

    if scan_id is None:
        conn = db._conn()
        row = conn.execute(
            "SELECT id FROM scans WHERE target LIKE ? ORDER BY id DESC LIMIT 1",
            ("%" + domain + "%",)
        ).fetchone()
        conn.close()
        if row:
            scan_id = row["id"]
    if scan_id is None:
        warn("No scan found in DB")
        return []

    findings = db.get_findings(scan_id)
    if only_severity:
        findings = [f for f in findings if f.get("severity") in only_severity]

    if not findings:
        info("No findings for this scan")
        return []

    info("Generating reports for " + str(len(findings)) + " finding(s)")
    generated = []

    for i, f in enumerate(findings, 1):
        md = build_report_md(f, domain)
        vuln_type = safe_filename(f.get("vuln_type", "finding"))
        fname = str(i) + "_" + vuln_type + "_" + f.get("severity", "unknown") + ".md"
        path = out_dir / fname

        try:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(md)
            db.add_report(f["id"], str(path), format="hackerone")
            generated.append(str(path))
            ok("Report: " + str(path))
        except Exception as e:
            warn("Failed to write report: " + str(e))

    ok("Total reports: " + str(len(generated)))
    return generated


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Report generator")
    p.add_argument("-t", "--target", required=True)
    p.add_argument("-s", "--scan-id", type=int, default=None)
    p.add_argument("-o", "--output", default="results")
    p.add_argument("--severity", default="critical,high,medium")
    args = p.parse_args()

    sev = [s.strip() for s in args.severity.split(",")] if args.severity else None
    files = generate_reports(args.target, args.scan_id, args.output, sev)
    print("\nGenerated " + str(len(files)) + " report(s).")