"""
reporting/report.py
-------------------
HackerOne / Bugcrowd report generator.
Pulls findings from SQLite, generates Markdown reports.
Optionally asks AI to polish the description.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional

from core.logger import get_logger, banner, info, ok, warn, skip
from core.utils import ensure_dir, save_json, safe_filename
from core.config_loader import get_config
from core.database import get_db
from reporting.cvss_calculator import cvss_for
from reporting.poc_generator import poc_for_finding

log = get_logger("report")
cfg = get_config()


H1_TEMPLATE = """# {title}

**Severity:** {severity} (CVSS {score})
**Vector:** `{vector}`
**Target:** {host}
**Vulnerability Type:** {vuln_type}

## Summary

{summary}

## Steps To Reproduce

{steps}

## Proof of Concept

### cURL

```bash
{curl_poc}
Raw HTTP Request
http
{raw_http_poc}
Python
python
{python_poc}
Impact
{impact}

Supporting Material
Full request/response captured by framework

Reference: {reference}

Remediation
{remediation}

Report generated by Dream Framework on {ts}
"""

def _severity_emoji(sev: str) -> str:
return {
"critical": "[CRIT]",
"high": "[HIGH]",
"medium": "[MED]",
"low": "[LOW]",
"info": "[INFO]",
}.get(sev.lower(), "[?]")

def build_report_md(finding: Dict, domain: str,
ai_text: Optional[Dict] = None) -> str:
vuln_type = finding.get("vuln_type", "unknown")
cvss = cvss_for(vuln_type)
url = finding.get("url", "")
param = finding.get("param", "")
payload = finding.get("payload", "")
evidence = finding.get("evidence", "")

from urllib.parse import urlparse
host = urlparse(url).netloc if url else domain

title = (ai_text.get("title") if ai_text else None) or
f"{vuln_type.replace('_', ' ').title()} in {host}"

severity = (ai_text.get("severity") if ai_text else None) or cvss["severity"]

summary = (ai_text.get("description") if ai_text else None) or
f"A {vuln_type} vulnerability was detected at {url}."

steps = (ai_text.get("steps_to_reproduce") if ai_text else None) or
_default_steps(url, param, payload)

impact = (ai_text.get("impact") if ai_text else None) or
_default_impact(vuln_type)

remediation = (ai_text.get("remediation") if ai_text else None) or
_default_remediation(vuln_type)

reference = _reference_url(vuln_type)
poc = poc_for_finding(finding)

return H1_TEMPLATE.format(
title=title,
severity=severity,
score=cvss["score"],
vector=cvss["vector"],
host=host,
vuln_type=vuln_type,
summary=summary,
steps=steps,
curl_poc=poc["curl"],
raw_http_poc=poc["raw_http"],
python_poc=poc["python"],
impact=impact,
reference=reference,
remediation=remediation,
ts=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
)

def _default_steps(url: str, param: str, payload: str) -> str:
lines = ["1. Navigate to the vulnerable endpoint:"]
lines.append(f" \n {url}\n")
if param and payload:
lines.append(f"2. Inject the following payload into parameter {param}:")
lines.append(f" \n {payload}\n")
lines.append("3. Observe the response confirming the vulnerability.")
lines.append("4. Reproduce using the cURL/Python PoC below.")
return "\n".join(lines)

def _default_impact(vuln_type: str) -> str:
v = vuln_type.lower()
if "sql" in v:
return "An attacker can read/modify database contents, potentially leading to full data breach or RCE."
if "rce" in v:
return "Full server compromise - attacker can execute arbitrary commands."
if "xss" in v:
return "Session hijacking, credential theft, or arbitrary actions in victim's browser."
if "ssrf" in v:
return "Internal network access, cloud metadata theft, or lateral movement."
if "idor" in v:
return "Unauthorized access to other users' data (privacy breach)."
if "takeover" in v:
return "An attacker can host arbitrary content on the target's subdomain."
if "jwt" in v:
return "Authentication bypass / privilege escalation."
if "oauth" in v:
return "Account takeover via redirect_uri abuse."
if "redirect" in v:
return "Phishing / token leakage."
if "xxe" in v:
return "File disclosure, SSRF, or DoS."
if "ssti" in v:
return "Remote code execution in template engine."
if "cache" in v:
return "Poisoned cached responses affecting all users."
return "Security impact varies based on context - review evidence."

def _default_remediation(vuln_type: str) -> str:
v = vuln_type.lower()
if "sql" in v:
return "Use parameterized queries / prepared statements."
if "xss" in v:
return "Context-aware output encoding and Content-Security-Policy."
if "ssrf" in v:
return "Whitelist allowed destinations, block link-local addresses, use IMDSv2."
if "idor" in v:
return "Enforce authorization checks on every object reference."
if "takeover" in v:
return "Remove dangling DNS records and reclaim provider resources."
if "jwt" in v:
return "Use strong secrets, reject 'none' alg, validate kid."
if "oauth" in v:
return "Strict redirect_uri whitelist; require state + PKCE."
if "redirect" in v:
return "Whitelist redirect targets; disallow open redirects."
if "xxe" in v:
return "Disable external entity processing (XXE)."
if "ssti" in v:
return "Never render user input as templates; use sandboxing."
if "cache" in v:
return "Include all relevant headers in cache key; strip unkeyed headers."
return "Apply defense-in-depth and follow OWASP guidelines."

def _reference_url(vuln_type: str) -> str:
v = vuln_type.lower()
refs = {
"xss": "https://owasp.org/www-community/attacks/xss/",
"sqli": "https://owasp.org/www-community/attacks/SQL_Injection",
"ssrf": "https://owasp.org/www-community/attacks/Server_Side_Request_Forgery",
"idor": "https://owasp.org/www-project-web-security-testing-guide/",
"jwt": "https://portswigger.net/web-security/jwt",
"oauth": "https://portswigger.net/web-security/oauth",
"xxe": "https://portswigger.net/web-security/xxe",
"ssti": "https://portswigger.net/web-security/server-side-template-injection",
"takeover": "https://github.com/EdOverflow/can-i-take-over-xyz",
}
for k, url in refs.items():
if k in v:
return url
return "https://owasp.org/www-project-top-ten/"

def ai_polish(finding: Dict, domain: str) -> Optional[Dict]:
try:
from core.ai_engine import ask_ai, is_ai_available
except Exception:
return None
if not is_ai_available():
return None
prompt = f"""
Write a HackerOne bug bounty report for this finding:

{json.dumps(finding, indent=2)[:3000]}

Return JSON:
{{
"title": "...",
"severity": "critical|high|medium|low",
"description": "2-3 sentence summary",
"steps_to_reproduce": "1. ...\n2. ...\n3. ...",
"impact": "...",
"remediation": "..."
}}
"""
return ask_ai(prompt)

def generate_reports(domain: str, scan_id: Optional[int] = None,
output_root: str = "results",
only_severity: Optional[List[str]] = None,
use_ai: bool = True) -> List[str]:
banner(f"REPORTS: {domain}")

out_dir = Path(output_root) / domain / "reports"
ensure_dir(out_dir)

db = get_db()

if scan_id is None:
conn = db._conn()
row = conn.execute(
"SELECT id FROM scans WHERE target LIKE ? ORDER BY id DESC LIMIT 1",
(f"%{domain}%",)
).fetchone()
conn.close()
if row:
scan_id = row["id"]
if scan_id is None:
warn("No scan found in DB")
return []

findings = db.get_findings(scan_id)
if only_severity:
findings = [f for f in findings if f.get("severity") in only_severity]

if not findings:
info("No findings for this scan")
return []

info(f"Generating reports for {len(findings)} finding(s)")
generated: List[str] = []

for i, f in enumerate(findings, 1):
if f.get("severity") == "info" and not (only_severity and "info" in only_severity):
continue

ai_text = ai_polish(f, domain) if use_ai else None
md = build_report_md(f, domain, ai_text=ai_text)

vuln_type = safe_filename(f.get("vuln_type", "finding"))
fname = f"{i:03d}{vuln_type}{f.get('severity', 'unknown')}.md"
path = out_dir / fname

try:
with open(path, "w", encoding="utf-8") as fh:
fh.write(md)
db.add_report(f["id"], str(path), format="hackerone")
generated.append(str(path))
ok(f"Report: {path}")
except Exception as e:
warn(f"Failed to write report: {e}")

ok(f"Total reports: {len(generated)} -> {out_dir}")
return generated

if name == "main":
import argparse
p = argparse.ArgumentParser(description="Report generator")
p.add_argument("-t", "--target", required=True)
p.add_argument("-s", "--scan-id", type=int, default=None)
p.add_argument("-o", "--output", default="results")
p.add_argument("--severity", default="critical,high,medium",
help="comma-separated severities to include")
p.add_argument("--no-ai", action="store_true")
args = p.parse_args()

sev = [s.strip() for s in args.severity.split(",")] if args.severity else None
files = generate_reports(args.target, args.scan_id, args.output,
only_severity=sev, use_ai=not args.no_ai)
print(f"\nGenerated {len(files)} report(s).")
